version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12.7
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running main.py..."
      - python main.py

artifacts:
  files:
    - '**/*'